version: '3'
#name: linguacafe

networks:
    proxy-network:
        external: "true"

volumes:
  linguacafe-webserver-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/blockstorage/linguacafe-webserver-data
      
services:
    webserver:
        container_name: linguacafe-webserver
        restart: unless-stopped
        build:
          context: .
          dockerfile: docker/PhpDockerfile
        depends_on:
            - mysql
        volumes:
            - linguacafe-webserver-data:/var/www/html
            - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
        environment:
            PYTHON_CONTAINER_NAME: linguacafe-python-service
            DB_DATABASE: "${LINGUACAFE_DB}"
            DB_USERNAME: "${LINGUACAFE_ROOT}"
            DB_PASSWORD: "${LINGUACAFE_PASSWORD}"
            VIRTUAL_HOST: "lernen.shivamnaik.de"
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: "lernen.shivamnaik.de"
            LETSENCRYPT_EMAIL: "ichbinshivamsnaik@outlook.com"
            DB_HOST: linguacafe-database
        ports:
            - 3009:3000
            - 9191:80
        networks:
            - proxy-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:latest
        container_name: linguacafe-database
        restart: unless-stopped
        tty: true
        ports:
          - "3308:3306"
        volumes:
          - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${LINGUACAFE_DB}"
            MYSQL_USER: "${LINGUACAFE_ROOT}"
            MYSQL_PASSWORD: "${LINGUACAFE_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${LINGUACAFE_ROOT_PASSWORD}"
            SERVICE_NAME: linguacafe
        networks:
            - proxy-network
    python:
        container_name: linguacafe-python-service 
        image: ghcr.io/shivamsnaik/linguacafe-python-service:latest
        command: "python3 /app/tokenizer.py"
        restart: unless-stopped
        tty: true
        ports: 
            - "8678:8678"
        volumes:
            - ./tools:/app
            - ./storage/app:/var/www/html/storage/app
        networks:
            - proxy-network
        environment:
            PYTHONPATH: "/var/www/html/storage/app/model"
